### ISSUE TITLE
Build can result in K8s Not found error 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#220]
```
io.kubernetes.client.openapi.ApiException: Not Found
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:971)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883)
	at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPodWithHttpInfo(CoreV1Api.java:45995)
	at io.kubernetes.client.openapi.apis.CoreV1Api.readNamespacedPod(CoreV1Api.java:45965)
	at io.seqera.wave.service.k8s.K8sServiceImpl.getPod(K8sServiceImpl.groovy:189)
	at io.seqera.wave.service.k8s.K8sServiceImpl.waitPod(K8sServiceImpl.groovy:366)
	at io.seqera.wave.service.builder.KubeBuildStrategy.build(KubeBuildStrategy.groovy:66)
	at io.seqera.wave.service.builder.ContainerBuildServiceImpl.launch(ContainerBuildServiceImpl.groovy:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at io.seqera.wave.service.builder.ContainerBuildServiceImpl$_launchAsync_lambda1.doCall(ContainerBuildServiceImpl.groovy:174)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by marcodelapierre** [comment]
@pditommaso is this still relevant? or was it fixed?

**Comment by gavinelder** [comment]
Closing we have seen this issue in ~2 years whilst I have been at the business.
