### ISSUE TITLE
Logs are not reported for failing build

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#327]
When a container build fail the logs are reported in the notification email but are not shown in the corresponding build page.

**Comment by pditommaso** [comment]
Indeed, currently, the upload is made only when the status is succeeded. Dont remember the rationale of that, but does not make much sense 

https://github.com/seqeralabs/wave/blob/9b4c0fd9e01abb01e547bac61227decc7ce4c6c6/src/main/groovy/io/seqera/wave/service/logs/BuildLogServiceImpl.groovy#L82-L88

**Comment by munishchouhan** [comment]
wave unit tests in my local machine starts failing in last couple of weeks, is there any change in passwords

```
Assertion failed: 

assert testcontainers0.execInContainer("apk","add", "docker","bash").exitCode==0
                       |                                             |       |
                       |                                             2       false
                       Container.ExecResult(exitCode=2, stdout=fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
                       fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
                       , stderr=WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/main: Permission denied
                       WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.18/community: Permission denied
                       ERROR: unable to select packages:
                         bash (no such package):
                           required by: world[bash]
                         docker (no such package):
                           required by: world[docker]
                       )

	at io.seqera.wave.test.DockerRegistryContainer$Trait$Helper.initRegistryContainer(DockerRegistryContainer.groovy:49)
	at io.seqera.wave.RegistryProxyServiceTest.setupSpec(RegistryProxyServiceTest.groovy:49)
```
