### ISSUE TITLE
Investigate frequent failure of Redis based Test in CI

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#398]
I have observed for past 2 weeks that  [RegistryControllerRedisTest](https://github.com/seqeralabs/wave/blob/b8498680008ad2dbdff1cbd059c1f12ec0e2534e/src/test/groovy/io/seqera/wave/controller/RegistryControllerRedisTest.groovy#L44) fails frequently 

Here are some runs:
https://github.com/seqeralabs/wave/actions/runs/7876160876
https://github.com/seqeralabs/wave/actions/runs/7847253637

<img width="846" alt="Screenshot 2024-02-12 at 19 20 48" src="https://github.com/seqeralabs/wave/assets/6575288/eafd8443-6b7b-411d-b7f0-1a00ecc355d9">

<img width="1087" alt="Screenshot 2024-02-12 at 19 26 38" src="https://github.com/seqeralabs/wave/assets/6575288/3b2b0a72-e8da-456b-8f95-daf1f1ca855d">

**Comment by munishchouhan** [comment]
happened again
https://github.com/seqeralabs/wave/actions/runs/7903733462
logs:
```
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at app//redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:251)
	at app//redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:47)
	at app//redis.clients.jedis.Protocol.process(Protocol.java:135)
	at app//redis.clients.jedis.Protocol.read(Protocol.java:221)
	at app//redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
	at app//redis.clients.jedis.Connection.getOne(Connection.java:333)
	at app//redis.clients.jedis.Connection.executeCommand(Connection.java:138)
	at app//redis.clients.jedis.Jedis.flushAll(Jedis.java:405)
	at app//io.seqera.wave.service.builder.BuildCacheStoreRedisTest.setup(BuildCacheStoreRedisTest.groovy:49)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
	at java.base/java.io.InputStream.read(InputStream.java:217)
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:245)
	... 8 more

```

**Comment by munishchouhan** [comment]
It failed in master now
https://github.com/seqeralabs/wave/actions/runs/7907711839
<img width="1799" alt="Screenshot 2024-02-15 at 09 24 08" src="https://github.com/seqeralabs/wave/assets/6575288/0274f16a-89a5-4e22-958d-68548db593aa">

**Comment by munishchouhan** [comment]
https://github.com/seqeralabs/wave/actions/runs/7933399445

**Comment by munishchouhan** [comment]
Another failure
https://github.com/seqeralabs/wave/actions/runs/8046026105/attempts/1

**Comment by munishchouhan** [comment]
closed in favor of https://github.com/seqeralabs/wave/issues/431
