### ISSUE TITLE
Report an actionable error message when request attribute is not base64 encoded 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#400]
When a request attribute is not base64 encoded as expected the following generic error is reported 

```
Feb-13 19:35:39.904 [io-executor-thread-3116] ERROR io.seqera.wave.ErrorHandler - bad character in base64 value - Error ID: 32b22d2aa802 - Request: POST /container-token
java.lang.RuntimeException: bad character in base64 value
	at org.codehaus.groovy.runtime.EncodingGroovyMethods.decodeBase64(EncodingGroovyMethods.java:281)
	at org.codehaus.groovy.runtime.EncodingGroovyMethods.decodeBase64(EncodingGroovyMethods.java:238)
	at io.seqera.wave.controller.ContainerTokenController.makeBuildRequest(ContainerTokenController.groovy:197)
	at io.seqera.wave.controller.ContainerTokenController.buildRequest(ContainerTokenController.groovy:228)
	at io.seqera.wave.controller.ContainerTokenController.makeRequestData(ContainerTokenController.groovy:269)
	at io.seqera.wave.controller.ContainerTokenController.makeResponse(ContainerTokenController.groovy:166)
	at io.seqera.wave.controller.ContainerTokenController.getToken(ContainerTokenController.groovy:146)
	at io.seqera.wave.controller.$ContainerTokenController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

The goal of this issue is to handle this condition and throw a BadRequestException with an actionable error message

**Comment by pditommaso** [comment]
Solved by 8ab29ee0
