### ISSUE TITLE
Handle AWS Timeout exception

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#437]
In some case the following exception can be thrown when authenticating the a ECR repository (not the stack trace is in reverse order). 

```
2024-04-02 10:26:39.397	
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-04-02 10:26:39.397	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-04-02 10:26:39.397	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-04-02 10:26:39.397	
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-04-02 10:26:39.397	
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
2024-04-02 10:26:39.397	
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
2024-04-02 10:26:39.397	
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
2024-04-02 10:26:39.397	
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
2024-04-02 10:26:39.397	
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
2024-04-02 10:26:39.397	
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
2024-04-02 10:26:39.397	
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
2024-04-02 10:26:39.397	
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
2024-04-02 10:26:39.397	
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
2024-04-02 10:26:39.397	
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
2024-04-02 10:26:39.397	
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
2024-04-02 10:26:39.397	
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
2024-04-02 10:26:39.397	
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
2024-04-02 10:26:39.397	
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
2024-04-02 10:26:39.397	
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
2024-04-02 10:26:39.397	
	at io.seqera.wave.controller.$RegistryProxyController$Definition$Exec.dispatch(Unknown Source)
2024-04-02 10:26:39.397	
	at io.seqera.wave.controller.RegistryProxyController.handleGet(RegistryProxyController.groovy:137)
2024-04-02 10:26:39.397	
	at io.seqera.wave.controller.RegistryProxyController.handleGet0(RegistryProxyController.groovy:162)
2024-04-02 10:26:39.397	
	at io.seqera.wave.controller.RegistryProxyController.manifestForPath(RegistryProxyController.groovy:250)
2024-04-02 10:26:39.397	
	at io.seqera.wave.core.RegistryProxyService.handleManifest(RegistryProxyService.groovy:117)
2024-04-02 10:26:39.397	
	at io.seqera.wave.core.RegistryProxyService.client(RegistryProxyService.groovy:99)
2024-04-02 10:26:39.397	
	at io.seqera.wave.core.RegistryProxyService.getCredentials(RegistryProxyService.groovy:111)
2024-04-02 10:26:39.397	
	at io.seqera.wave.auth.RegistryCredentialsProviderImpl.getUserCredentials(RegistryCredentialsProviderImpl.groovy:122)
2024-04-02 10:26:39.397	
	at io.seqera.wave.auth.RegistryCredentialsProviderImpl.getUserCredentials0(RegistryCredentialsProviderImpl.groovy:128)
2024-04-02 10:26:39.397	
	at io.seqera.wave.auth.RegistryCredentialsFactoryImpl.create(RegistryCredentialsFactoryImpl.groovy:44)
2024-04-02 10:26:39.397	
	at io.seqera.wave.service.aws.AwsEcrService.getLoginToken(AwsEcrService.groovy:132)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313)
2024-04-02 10:26:39.397	
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571)
2024-04-02 10:26:39.397	
	at io.seqera.wave.service.aws.AwsEcrService$1.load(AwsEcrService.groovy)
2024-04-02 10:26:39.397	
	at io.seqera.wave.service.aws.AwsEcrService$1.load(AwsEcrService.groovy:74)
2024-04-02 10:26:39.397	
	at io.seqera.wave.service.aws.AwsEcrService.getLoginToken1(AwsEcrService.groovy:111)
2024-04-02 10:26:39.397	
	at software.amazon.awssdk.services.ecrpublic.DefaultEcrPublicClient.getAuthorizationToken(DefaultEcrPublicClient.java:849)
2024-04-02 10:26:39.397	
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
2024-04-02 10:26:39.397	
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
2024-04-02 10:26:39.397	
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
2024-04-02 10:26:39.397	
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:196)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
2024-04-02 10:26:39.396	
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
2024-04-02 10:26:39.396	
08:26:39.396 [io-executor-thread-11518] ERROR io.seqera.wave.ErrorHandler - User: arn:aws:iam::0000000000000:user/SomeRoleName is not authorized to perform: ecr-public:GetAuthorizationToken on resource: * because no identity-based policy allows the ecr-public:GetAuthorizationToken action (Service: EcrPublic, Status Code: 400, Request ID: xxxx) - Error ID: 9e9d25d88fbd - Request: GET /v2/wt/some/container/manifests/v1.5.0-pre2
```

**Comment by pditommaso** [comment]
Solved by 06141219
