### ISSUE TITLE
Fix Redis falky tests

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#458]
After applying https://github.com/seqeralabs/wave/pull/436

I see redis flaky test still happening here
https://github.com/seqeralabs/wave/actions/runs/8723403557

<img width="1068" alt="Screenshot 2024-04-17 at 16 27 28" src="https://github.com/seqeralabs/wave/assets/6575288/5cce7f23-d1a9-4556-ba88-0f87793d96a2">

```
should get and put key values

redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at app//redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:251)
	at app//redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:47)
	at app//redis.clients.jedis.Protocol.process(Protocol.java:135)
	at app//redis.clients.jedis.Protocol.read(Protocol.java:221)
	at app//redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
	at app//redis.clients.jedis.Connection.getOne(Connection.java:333)
	at app//redis.clients.jedis.Connection.executeCommand(Connection.java:138)
	at app//redis.clients.jedis.Jedis.flushAll(Jedis.java:405)
	at app//io.seqera.wave.service.builder.BuildCacheStoreRedisTest.setup(BuildCacheStoreRedisTest.groovy:49)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:313)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1025)
	at java.base/java.io.InputStream.read(InputStream.java:217)
	at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:245)
	... 8 more

```

**Comment by munishchouhan** [comment]
Tests are still failing 
https://github.com/seqeralabs/wave/actions/runs/8783049470/attempts/1

I will dig more, to see what else we can do
