### ISSUE TITLE
NPE when parsing container coordinates

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#463]
In some cases the following error is reported when parsing the container coordinates 

```
2024-04-22 14:04:53.703	
12:04:53.703 [io-executor-thread-13349] ERROR io.seqera.wave.ErrorHandler - Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null - Error ID: b5be15d8307f - Request: POST /v1alpha1/inspect
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
	at io.seqera.wave.util.StringUtils.getUrlProtocol(StringUtils.groovy:67)
	at io.seqera.wave.model.ContainerCoordinates.parse(ContainerCoordinates.groovy:55)
	at io.seqera.wave.service.inspect.ContainerInspectServiceImpl.containerSpec(ContainerInspectServiceImpl.groovy:220)
	at io.seqera.wave.controller.InspectController.makeResponse(InspectController.groovy:105)
	at io.seqera.wave.controller.InspectController.inspect(InspectController.groovy:89)
	at io.seqera.wave.controller.$InspectController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by munishchouhan** [comment]
@pditommaso is it from the wave production?

**Comment by munishchouhan** [comment]
its happening here https://github.com/seqeralabs/wave/blob/d9fb29429e8092c739baadac8a4004460d617ba0/src/main/groovy/io/seqera/wave/util/StringUtils.groovy#L67

**Comment by pditommaso** [comment]
Yep, it seems when it's missing the `containerImage` field

**Comment by munishchouhan** [comment]
I am fixing it here
https://github.com/seqeralabs/wave/pull/465
