### ISSUE TITLE
Invalid request path flooding the logs

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#545]
```
	
2024-06-26 19:37:31.296	
17:37:31.295 [io-executor-thread-9249] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Invalid request path '/v2/wt/XXXXXXXX//manifests/latest'
io.seqera.wave.exception.NotFoundException: Invalid request path '/v2/wt/XXXXXX//manifests/latest'
	at io.seqera.wave.core.RouteHandler.parse(RouteHandler.groovy:50)
	at io.seqera.wave.controller.RegistryProxyController.handleGet(RegistryProxyController.groovy:123)
	at io.seqera.wave.controller.$RegistryProxyController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:129)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by munishchouhan** [comment]
tried on local:
% docker pull docker.io/library/fastqc:0.11.9--0

What's next:
```
    View a summary of image vulnerabilities and recommendations → docker scout quickview docker.io/library/fastqc:0.11.9--0
Error response from daemon: pull access denied for fastqc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by munishchouhan** [comment]
not happening anymore
