### ISSUE TITLE
Exception Cannot invoke "java.util.Map.get(Object)" because "record" is null

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/wave#578]
The following exception should be managed better 

```
024-07-25 13:50:17.691	11:50:17.691 [io-executor-thread-59] ERROR io.seqera.wave.ErrorHandler - Cannot invoke "java.util.Map.get(Object)" because "record" is null - Error ID: fc04becb7b3a - Request: POST /v1alpha2/container
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "record" is null
	at io.seqera.wave.core.ContainerAugmenter.findTargetDigest(ContainerAugmenter.groovy:400)
	at io.seqera.wave.core.ContainerAugmenter.findImageManifestAndDigest(ContainerAugmenter.groovy:234)
	at io.seqera.wave.core.ContainerAugmenter.getContainerSpec(ContainerAugmenter.groovy:528)
	at io.seqera.wave.service.inspect.ContainerInspectServiceImpl.fetchConfig0(ContainerInspectServiceImpl.groovy:220)
	at io.seqera.wave.service.inspect.ContainerInspectServiceImpl.containerEntrypoint(ContainerInspectServiceImpl.groovy:191)
	at io.seqera.wave.service.builder.FreezeServiceImpl.appendEntrypoint(FreezeServiceImpl.groovy:70)
	at io.seqera.wave.service.builder.FreezeServiceImpl.createBuildFile(FreezeServiceImpl.groovy:53)
	at io.seqera.wave.service.builder.FreezeServiceImpl.freezeBuildRequest(FreezeServiceImpl.groovy:84)
	at io.seqera.wave.controller.ContainerController.makeRequestData(ContainerController.groovy:389)
	at io.seqera.wave.controller.ContainerController.handleRequest(ContainerController.groovy:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at io.seqera.wave.controller.ContainerController$_getContainerImpl_lambda1.doCall(ContainerController.groovy:199)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:47)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by munishchouhan** [comment]
This happened when I tried to create singularity image with fusion for platform linux/arm64

**Comment by pditommaso** [comment]
Ok, I've made a patch. Please give a try to check if the error reported is better

**Comment by munishchouhan** [comment]
> Ok, I've made a patch. Please give a try to check if the error reported is better

ok sure

**Comment by munishchouhan** [comment]
completed here https://github.com/seqeralabs/wave/pull/579
