### ISSUE TITLE
Condalock extraction error

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave#684]
getting this while testing:

2024-10-10 15:56:26 | 13:56:26.327 [io-executor-thread-178] WARN  i.s.w.s.logs.BuildLogServiceImpl - Unable to extract conda lock file from logs - reason: Range [18, -1) out of bounds for length 3299 java.lang.StringIndexOutOfBoundsException: Range [18, -1) out of bounds for length 3299 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) 	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) 	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) 	at java.base/java.lang.String.substring(String.java:2834) 	at io.seqera.wave.service.logs.BuildLogServiceImpl.extractCondaLockFile(BuildLogServiceImpl.groovy:196) 	at io.seqera.wave.service.logs.BuildLogServiceImpl.storeCondaLock(BuildLogServiceImpl.groovy:152) 	at io.seqera.wave.service.logs.BuildLogServiceImpl.storeLog(BuildLogServiceImpl.groovy:115) 	at io.seqera.wave.service.logs.BuildLogServiceImpl$_onBuildEvent_lambda1.doCall(BuildLogServiceImpl.groovy:102) 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) 	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141) 	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:196) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) 	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by pditommaso** [comment]
use markdown formatting
